[package]
name = "cal-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.27.0"
actix-web = "4.0.1"
clap = { version = "3.1.6", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }



